# =============================================================================
# Bibliometrix Comprehensive Analysis Script
# Generated by the Bibliometric Analysis Pipeline
# =============================================================================
# Install if needed: install.packages("bibliometrix")

library(bibliometrix)

# --- Configuration ---
# Resolve paths relative to this script's location (output/)
script_dir <- tryCatch(
  dirname(sys.frame(1)$ofile),
  error = function(e) {
    if (requireNamespace("rstudioapi", quietly = TRUE) &&
        rstudioapi::isAvailable()) {
      dirname(rstudioapi::getSourceEditorContext()$path)
    } else {
      getwd()
    }
  }
)
csv_path <- file.path(script_dir, "bibliometrix_export.csv")
output_dir <- file.path(script_dir, "figures")
dir.create(output_dir, showWarnings = FALSE, recursive = TRUE)

if (!file.exists(csv_path)) {
  alt <- file.path(getwd(), "output", "bibliometrix_export.csv")
  if (file.exists(alt)) {
    csv_path <- alt
    output_dir <- file.path(getwd(), "output", "figures")
    dir.create(output_dir, showWarnings = FALSE, recursive = TRUE)
  } else {
    stop("bibliometrix_export.csv not found. Run 'python main.py --phases 5' first.")
  }
}

cat("=== Bibliometrix Comprehensive Analysis ===\n")
cat("CSV:", csv_path, "\n")
cat("Output:", output_dir, "\n\n")

# --- 1. Load & Preprocess Data ---
cat("1. Loading data...\n")
M <- read.csv(csv_path, stringsAsFactors = FALSE)

# Replace NA with empty strings in ALL character columns
for (col in colnames(M)) {
  if (is.character(M[[col]])) {
    M[[col]][is.na(M[[col]])] <- ""
  }
}

# Ensure required fields
if (!"DB" %in% colnames(M)) M$DB <- "ISI"
M$DB[M$DB == ""] <- "ISI"
M$DT[M$DT == "" | is.na(M$DT)] <- "ARTICLE"

# Remove auxiliary columns that collide with bibliometrix internals
if ("AU1_CO" %in% colnames(M)) M$AU1_CO <- NULL

# Mark truly empty DE/ID as NA so strsplit doesn't produce phantom "" keywords
M$DE[M$DE == ""] <- NA
M$ID[M$ID == ""] <- NA
M$CR[M$CR == ""] <- NA

# Normalize separators: ensure "; " (semicolon + space)
for (col in c("DE", "ID", "CR", "C1")) {
  if (col %in% colnames(M)) {
    M[[col]] <- gsub("\\s*;\\s*", "; ", M[[col]])
  }
}

# Extract AU_CO from C1 (country = last token after final comma)
M <- metaTagExtraction(M, Field = "AU_CO", sep = ";")
if ("AU_CO" %in% colnames(M)) {
  M$AU_CO[is.na(M$AU_CO)] <- ""
}

# Also extract first author field (AU_UN = university, SR = short reference)
tryCatch({
  M <- metaTagExtraction(M, Field = "AU_UN", sep = ";")
  M <- metaTagExtraction(M, Field = "SR", sep = ";")
}, error = function(e) {})

cat("  Articles loaded:", nrow(M), "\n")
cat("  Year range:", min(M$PY, na.rm=TRUE), "-", max(M$PY, na.rm=TRUE), "\n")
cat("  Articles with keywords (DE):", sum(!is.na(M$DE)), "/", nrow(M), "\n")
cat("  Articles with references (CR):", sum(!is.na(M$CR)), "/", nrow(M), "\n\n")

# --- 2. Basic Bibliometric Analysis ---
cat("2. Running biblioAnalysis...\n")
tryCatch({
  results <- biblioAnalysis(M, sep = ";")
  pdf(file.path(output_dir, "01_basic_analysis.pdf"), width = 12, height = 8)
  S <- summary(results, k = 15, pause = FALSE)
  plot(x = results, k = 15, pause = FALSE)
  dev.off()
  cat("  Saved: 01_basic_analysis.pdf\n\n")
}, error = function(e) cat("  Error in basic analysis:", e$message, "\n\n"))

# --- 3. Co-citation Network ---
cat("3. Building co-citation network...\n")
tryCatch({
  NetMatrix_cocit <- biblioNetwork(M, analysis = "co-citation",
                                    network = "references", sep = ";")
  if (!is.null(NetMatrix_cocit) && nrow(NetMatrix_cocit) > 3) {
    n_plot <- min(30, nrow(NetMatrix_cocit))
    pdf(file.path(output_dir, "02_cocitation_network.pdf"), width = 14, height = 12)
    net_cocit <- networkPlot(NetMatrix_cocit, n = n_plot, type = "fruchterman",
                              Title = "Co-Citation Network",
                              size.cex = TRUE, size = 15,
                              label.cex = TRUE, labelsize = 1.2,
                              cluster = "louvain", edges.min = 2)
    dev.off()
    cat("  Saved: 02_cocitation_network.pdf\n")
  } else {
    cat("  Co-citation matrix too small, skipping.\n")
  }
}, error = function(e) cat("  Error in co-citation:", e$message, "\n"))

# --- 4. Keyword Co-occurrence Network ---
cat("4. Building keyword co-occurrence network...\n")
tryCatch({
  # Only use articles that have keywords
  M_kw <- M[!is.na(M$DE) & M$DE != "", ]
  if (nrow(M_kw) >= 5) {
    NetMatrix_kw <- biblioNetwork(M_kw, analysis = "co-occurrences",
                                   network = "keywords", sep = ";")
    if (!is.null(NetMatrix_kw) && nrow(NetMatrix_kw) > 3) {
      n_plot <- min(30, nrow(NetMatrix_kw))
      pdf(file.path(output_dir, "03_keyword_cooccurrence.pdf"), width = 14, height = 12)
      net_kw <- networkPlot(NetMatrix_kw, n = n_plot, type = "fruchterman",
                             Title = "Keyword Co-occurrence Network",
                             size.cex = TRUE, size = 12,
                             label.cex = TRUE, labelsize = 1.0,
                             cluster = "louvain", edges.min = 2)
      dev.off()
      cat("  Saved: 03_keyword_cooccurrence.pdf\n")
    } else {
      cat("  Keyword matrix too small.\n")
    }
  } else {
    cat("  Not enough articles with keywords.\n")
  }
}, error = function(e) cat("  Error in keyword network:", e$message, "\n"))

# --- 5. Bibliographic Coupling ---
cat("5. Building bibliographic coupling network...\n")
tryCatch({
  NetMatrix_coup <- biblioNetwork(M, analysis = "coupling",
                                   network = "references", sep = ";")
  if (!is.null(NetMatrix_coup) && nrow(NetMatrix_coup) > 3) {
    n_plot <- min(30, nrow(NetMatrix_coup))
    pdf(file.path(output_dir, "04_bibliographic_coupling.pdf"), width = 14, height = 12)
    net_coup <- networkPlot(NetMatrix_coup, n = n_plot, type = "fruchterman",
                             Title = "Bibliographic Coupling Network",
                             size.cex = TRUE, size = 15, cluster = "louvain")
    dev.off()
    cat("  Saved: 04_bibliographic_coupling.pdf\n")
  } else {
    cat("  Coupling matrix too small.\n")
  }
}, error = function(e) cat("  Error in coupling:", e$message, "\n"))

# --- 6. Thematic Map (Strategic Diagram) ---
cat("6. Creating thematic map...\n")
tryCatch({
  M_tm <- M[!is.na(M$DE) & M$DE != "", ]
  if (nrow(M_tm) >= 10) {
    Map <- thematicMap(M_tm, field = "DE", n = 200, minfreq = 3,
                       stemming = FALSE, size = 0.5, repel = TRUE)
    pdf(file.path(output_dir, "05_thematic_map.pdf"), width = 14, height = 10)
    print(Map$map)
    dev.off()
    cat("  Saved: 05_thematic_map.pdf\n")
  } else {
    cat("  Not enough articles with keywords for thematic map.\n")
  }
}, error = function(e) cat("  Error in thematic map:", e$message, "\n"))

# --- 7. Thematic Evolution ---
cat("7. Creating thematic evolution...\n")
tryCatch({
  M_te <- M[!is.na(M$DE) & M$DE != "", ]
  years <- sort(unique(M_te$PY))
  if (length(years) >= 4) {
    # Build explicit year breaks ensuring uniqueness
    yr_min <- min(years)
    yr_max <- max(years)
    yr_mid <- floor(median(years))
    # Ensure 3 distinct breaks for 2 time slices
    cuts <- unique(c(yr_min, yr_mid, yr_max))
    if (length(cuts) >= 3) {
      nexus <- thematicEvolution(M_te, field = "DE", years = cuts,
                                  n = 200, minFreq = 2)
      pdf(file.path(output_dir, "06_thematic_evolution.pdf"), width = 16, height = 10)
      plotThematicEvolution(nexus$Nodes, nexus$Edges)
      dev.off()
      cat("  Saved: 06_thematic_evolution.pdf\n")
    } else {
      cat("  Not enough distinct year breaks.\n")
    }
  } else {
    cat("  Not enough year range for thematic evolution.\n")
  }
}, error = function(e) cat("  Error in thematic evolution:", e$message, "\n"))

# --- 8. Historiograph ---
cat("8. Creating historiograph...\n")
tryCatch({
  histResults <- histNetwork(M, min.citations = 1, sep = ";")
  if (!is.null(histResults$NetMatrix) &&
      is.matrix(histResults$NetMatrix) &&
      nrow(histResults$NetMatrix) > 1) {
    pdf(file.path(output_dir, "07_historiograph.pdf"), width = 16, height = 10)
    net_hist <- histPlot(histResults, n = 25, size = 5, labelsize = 3)
    dev.off()
    cat("  Saved: 07_historiograph.pdf\n")
  } else {
    cat("  Historiograph: not enough citation matches in corpus.\n")
    cat("  (histNetwork needs CR entries to match 'AUTHOR, YEAR, JOURNAL' of corpus articles)\n")
  }
}, error = function(e) cat("  Error in historiograph:", e$message, "\n"))

# --- 9. Country Collaboration Network ---
cat("9. Building country collaboration network...\n")
tryCatch({
  NetMatrix_country <- biblioNetwork(M, analysis = "collaboration",
                                      network = "countries", sep = ";")
  if (!is.null(NetMatrix_country) && nrow(NetMatrix_country) > 2) {
    n_plot <- min(30, nrow(NetMatrix_country))
    pdf(file.path(output_dir, "08_country_collaboration.pdf"), width = 14, height = 12)
    net_country <- networkPlot(NetMatrix_country, n = n_plot, type = "circle",
                                Title = "Country Collaboration Network",
                                size.cex = TRUE, size = 15,
                                cluster = "louvain",
                                label.cex = TRUE, labelsize = 1.5)
    dev.off()
    cat("  Saved: 08_country_collaboration.pdf\n")
  } else {
    cat("  Country network too small.\n")
  }
}, error = function(e) cat("  Error in country network:", e$message, "\n"))

# --- 10. Conceptual Structure (MCA) ---
cat("10. Conceptual structure analysis...\n")
tryCatch({
  M_cs <- M[!is.na(M$DE) & M$DE != "", ]
  if (nrow(M_cs) >= 10) {
    pdf(file.path(output_dir, "09_conceptual_structure.pdf"), width = 14, height = 10)
    CS <- conceptualStructure(M_cs, field = "DE", method = "MCA",
                               minDegree = 3, clust = "auto",
                               k.max = 8, stemming = FALSE,
                               labelsize = 10, documents = 15)
    dev.off()
    cat("  Saved: 09_conceptual_structure.pdf\n")
  } else {
    cat("  Not enough articles with keywords for conceptual structure.\n")
  }
}, error = function(e) {
  dev.off()
  cat("  Error in conceptual structure:", e$message, "\n")
})

# --- 11. Three Fields Plot (Sankey AU-DE-SO) ---
cat("11. Creating three fields plot...\n")
tryCatch({
  M_tf <- M[!is.na(M$DE) & M$DE != "", ]
  if (nrow(M_tf) >= 10) {
    pdf(file.path(output_dir, "10_three_fields_plot.pdf"), width = 16, height = 10)
    threeFieldsPlot(M_tf, fields = c("AU", "DE", "SO"), n = c(15, 15, 15))
    dev.off()
    cat("  Saved: 10_three_fields_plot.pdf\n")
  } else {
    cat("  Not enough articles with keywords for three fields plot.\n")
  }
}, error = function(e) {
  dev.off()
  cat("  Error in three fields plot:", e$message, "\n")
})

# --- 12. Author Collaboration Network ---
cat("12. Building author collaboration network...\n")
tryCatch({
  NetMatrix_auth <- biblioNetwork(M, analysis = "collaboration",
                                   network = "authors", sep = ";")
  if (!is.null(NetMatrix_auth) && nrow(NetMatrix_auth) > 3) {
    n_plot <- min(30, nrow(NetMatrix_auth))
    pdf(file.path(output_dir, "11_author_collaboration.pdf"), width = 14, height = 12)
    net_auth <- networkPlot(NetMatrix_auth, n = n_plot, type = "fruchterman",
                             Title = "Author Collaboration Network",
                             size.cex = TRUE, size = 12,
                             cluster = "louvain",
                             label.cex = TRUE, labelsize = 1.0)
    dev.off()
    cat("  Saved: 11_author_collaboration.pdf\n")
  } else {
    cat("  Author network too small.\n")
  }
}, error = function(e) cat("  Error in author network:", e$message, "\n"))

# --- 12b. Institution Collaboration Network ---
cat("12b. Building institution collaboration network...\n")
tryCatch({
  NetMatrix_inst <- biblioNetwork(M, analysis = "collaboration",
                                   network = "universities", sep = ";")
  if (!is.null(NetMatrix_inst) && nrow(NetMatrix_inst) > 3) {
    n_plot <- min(30, nrow(NetMatrix_inst))
    pdf(file.path(output_dir, "12b_institution_collaboration.pdf"), width = 14, height = 12)
    net_inst <- networkPlot(NetMatrix_inst, n = n_plot, type = "fruchterman",
                             Title = "Institution Collaboration Network",
                             size.cex = TRUE, size = 12,
                             cluster = "louvain",
                             label.cex = TRUE, labelsize = 0.9)
    dev.off()
    cat("  Saved: 12b_institution_collaboration.pdf\n")
  } else {
    cat("  Institution network too small.\n")
  }
}, error = function(e) cat("  Error in institution network:", e$message, "\n"))

# --- 12c. Bibliographic Coupling by Sources (Journals) ---
cat("12c. Building bibliographic coupling by sources...\n")
tryCatch({
  NetMatrix_coup_src <- biblioNetwork(M, analysis = "coupling",
                                       network = "sources", sep = ";")
  if (!is.null(NetMatrix_coup_src) && nrow(NetMatrix_coup_src) > 3) {
    n_plot <- min(30, nrow(NetMatrix_coup_src))
    pdf(file.path(output_dir, "12c_coupling_sources.pdf"), width = 14, height = 12)
    net_coup_src <- networkPlot(NetMatrix_coup_src, n = n_plot, type = "fruchterman",
                                 Title = "Bibliographic Coupling (Sources/Journals)",
                                 size.cex = TRUE, size = 15, cluster = "louvain")
    dev.off()
    cat("  Saved: 12c_coupling_sources.pdf\n")
  } else {
    cat("  Coupling by sources matrix too small.\n")
  }
}, error = function(e) cat("  Error in coupling by sources:", e$message, "\n"))

# --- 12d. Bibliographic Coupling by Countries ---
cat("12d. Building bibliographic coupling by countries...\n")
tryCatch({
  NetMatrix_coup_co <- biblioNetwork(M, analysis = "coupling",
                                      network = "countries", sep = ";")
  if (!is.null(NetMatrix_coup_co) && nrow(NetMatrix_coup_co) > 2) {
    n_plot <- min(30, nrow(NetMatrix_coup_co))
    pdf(file.path(output_dir, "12d_coupling_countries.pdf"), width = 14, height = 12)
    net_coup_co <- networkPlot(NetMatrix_coup_co, n = n_plot, type = "circle",
                                Title = "Bibliographic Coupling (Countries)",
                                size.cex = TRUE, size = 15, cluster = "louvain",
                                label.cex = TRUE, labelsize = 1.3)
    dev.off()
    cat("  Saved: 12d_coupling_countries.pdf\n")
  } else {
    cat("  Coupling by countries matrix too small.\n")
  }
}, error = function(e) cat("  Error in coupling by countries:", e$message, "\n"))

# --- 12e. Co-citation by Sources (Journals) ---
cat("12e. Building co-citation by sources...\n")
tryCatch({
  NetMatrix_cocit_src <- biblioNetwork(M, analysis = "co-citation",
                                        network = "sources", sep = ";")
  if (!is.null(NetMatrix_cocit_src) && nrow(NetMatrix_cocit_src) > 3) {
    n_plot <- min(30, nrow(NetMatrix_cocit_src))
    pdf(file.path(output_dir, "12e_cocitation_sources.pdf"), width = 14, height = 12)
    net_cocit_src <- networkPlot(NetMatrix_cocit_src, n = n_plot, type = "fruchterman",
                                  Title = "Co-citation Network (Sources/Journals)",
                                  size.cex = TRUE, size = 15,
                                  label.cex = TRUE, labelsize = 1.1,
                                  cluster = "louvain", edges.min = 2)
    dev.off()
    cat("  Saved: 12e_cocitation_sources.pdf\n")
  } else {
    cat("  Co-citation by sources matrix too small.\n")
  }
}, error = function(e) cat("  Error in co-citation by sources:", e$message, "\n"))

# --- 13. Most Cited References ---
cat("13. Most cited references...\n")
tryCatch({
  CR <- citations(M, field = "article", sep = ";")
  if (!is.null(CR) && is.data.frame(CR) && nrow(CR) > 0 &&
      "Freq" %in% colnames(CR) && any(CR$Freq > 0)) {
    n_top <- min(20, nrow(CR))
    pdf(file.path(output_dir, "12_most_cited_references.pdf"), width = 14, height = 8)
    par(mar = c(5, 18, 4, 2))
    barplot(CR$Freq[1:n_top],
            names.arg = substr(CR$Cited[1:n_top], 1, 45),
            horiz = TRUE, las = 1, cex.names = 0.65,
            main = "Most Cited References in the Corpus",
            xlab = "Citations", col = "#4e79a7")
    dev.off()
    cat("  Saved: 12_most_cited_references.pdf\n")
  } else {
    cat("  No valid citation data for barplot.\n")
  }
}, error = function(e) cat("  Error in cited references:", e$message, "\n"))

# --- Summary ---
cat("\n=== Analysis Complete ===\n")
cat("Output files saved to:", output_dir, "\n")
cat("Generated PDFs:\n")
pdfs <- list.files(output_dir, pattern = "\\.pdf$", full.names = FALSE)
for (p in pdfs) cat("  -", p, "\n")

# --- Optional: Launch Biblioshiny ---
# Uncomment the line below to launch the interactive Biblioshiny app:
# biblioshiny()

cat("\nTo launch interactive analysis, run: biblioshiny()\n")
